language: go
go:
  - master

env:
  - GO111MODULE=on

dist: trusty
sudo: false
install: true
script:
  - go build -a -o $GOPATH/bin/password-manager github.com/lpegoraro/password-manager/password-manager
  - go test ./...