name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Setup environment
      runs: export GO111MODULE=on

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: go test -coverprofile=coverage.out ./...

    - name: Build
      run: go build -a -o $GOPATH/bin/password-manager github.com/lpegoraro/password-manager/password-manager
